import numpy as np
import struct
import argparse
import re

from datetime import datetime

def convertBytestoTemperature(rawTemp: bytearray, precision: int = 2) -> float:
    rawTemp = (int.from_bytes(rawTemp,'little')) >> 4
    floatTemp =  rawTemp * 503.975 / 4096 - 273.15
    return np.round(floatTemp,precision)

def convertBytesToVCCInt(rawVcc: bytearray, precision: int = 2) -> float :
    rawVcc = (int.from_bytes(rawVcc,'little')) >> 4
    floatVcc = rawVcc / 4096 * 3
    return np.round(floatVcc, precision)

def convertBytesToADCVal(rawADC: bytearray) -> float:
    return int.from_bytes(rawADC,'big') / 4096 * 3.3

def decode(packet: bytearray):
    """ Housekeeping Packet Format:
        8 Bytes FSW UTC Time
        4 Bytes FPGA Counter Time
        18 Bytes ADC: 2 Sync Bytes (\x10\x10) + 2 Bytes per 8 Channels
        14 Bytes FPGA: 2 Sync Bytes (\x0c\x0c) + 3 FPGA Temp Reads + 3 FPGA VCC Reads
        0x to 3x: 14 Bytes FPGA Counter: 2 Bytes Layer ID (e.g. Layer 2 = \x02\x02), 4 Bytes each Frame, Idle, Wronglength Counter"""
    fswtime = datetime.fromtimestamp(struct.unpack('d',packet[0:7])[0],tz=timezone.utc)
    fpgatime = int.from_bytes(packet[8:11],'little')
    
    ADCvalues = [convertBytesToADCVal(packet[14:29][i : i + 2]) for i in range(0,16,2)]
    L0Temp = ADCvalues[3] # missing calibration
    L1Temp = ADCvalues[2] # missing calibration
    L2Temp = ADCvalues[1] # missing calibration
    SecVolt = ADCvalues[0] * 2. 
    HVMon = ADCvalues[7] / 0.0125
    L0Current = ADCvalues[4] / 10.
    L1Current = ADCvalues[5] / 10.
    L2Current = ADCvalues[6] / 10.

    fpgatemp = np.average([convertBytesToFPGATemperature(packet[32:37][i : i + 2]) for i in range(0, 6, 2)])
    fpgaVCCInt = np.average([convertBytesToVCCInt(packet[38:43][i : i + 2]) for i in range(0, 6, 2)])

    counterBytes = packet[44:]
    layerinfo = [counterBytes[i:i+14] for i in range(0,len(counterBytes),14)]
    L0Frames = L0Idle = L0Wrong = 0
    L1Frames = L1Idle = L1Wrong = 0
    L2Frames = L2Idle = L2Wrong = 0

    for l in layerinfo:
        if l[0] == 0:
            L0Frames = int.from_bytes(l[2:5],'little')
            L0Idle = int.from_bytes(l[6:9],'little')
            L0Wrong = int.from_bytes(l[10:13],'little')
        elif l[0] == 1:
            L1Frames = int.from_bytes(l[2:5],'little')
            L1Idle = int.from_bytes(l[6:9],'little')
            L1Wrong = int.from_bytes(l[10:13],'little')
        elif l[0] == 2:
            L2Frames = int.from_bytes(l[2:5],'little')
            L2Idle = int.from_bytes(l[6:9],'little')
            L2Wrong = int.from_bytes(l[10:13],'little')

    hk_data = [fswtime,fpgatime,fpgatemp,fpgaVCCInt,SecVolt,HVMon,L0Temp,L1Temp,L2Temp,
               L0Current,L1Current,L2Current,L0Frames,L0Idle,L0Wrong,L1Frames,L1Idle,L1Wrong,L2Frames,L2Idle,L2Wrong]
    return hk_data

def identify_index(data):
    """Use pre-defined sync bytes to identify and extract housekeeping indexes"""
    mask_one = b'\x10\x10'
    mask_two = b'\x0c\x0c'
    pattern = re.compile(re.escape(mask1) + b'.{' + str(16).encode() + b'}' + re.escape(mask2), re.DOTALL)
    matched = re.finditer(pattern,data)
    return [m.start() - 12 for m in matched]

def main(args):
    read_file=open(args.filename,'rb')
    data = read_file.read()
    read_file.close()
    
    write_file=open(args.filename.replace('.bin','.csv'),'w')
    header = ['fswtime','fpgatime','fpgatemp','fpgaVCCInt','SecVolt','HVMon','L0Temp','L1Temp','L2Temp',
              'L0Current','L1Current','L2Current','L0Frames','L0Idle','L0Wrong','L1Frames','L1Idle','L1Wrong','L2Frames','L2Idle','L2Wrong']
    headerstring = ','.join(header)
    write_file.write(f'{headerstring}\n')
    
    pkt_indices = identify_index(data)
    packages = [data[i:j] for i,j in zip([0] + pkt_indices, pkt_indices + [None])]

    for p in packages:
        decoded_hit = decode(p)
        decoded_string=','.join(str(x) for x in decoded_hit)
        write_file.write(f'{decoded_string}\n')

    write_file.close()

if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description="Decode housekeeping data for astep generated by astep-fw and writes to .csv file")

    parser.add_argument(
        'filename',
        type=str,
        help='Input filename to decode, required to run'
    )

    args = parser.parse_args()
    main(args)

